### PR TITLE
fix: refresh proposal after casting an offchain vote

### LINKED ISSUE #101: fix(ux): auto-refresh results after offchain votes
- offchain spaces: trigger immediately on vote success
- onchain spaces: trigger after transaction validation

### PR DESCRIPTION
**Pull request by wa0x6e**
### Summary

Closes: #235
Also fix #101 partially

Fix an issue where your freshly vote is not taken into account when computing anything relative to the proposal's total score, because the proposal is no refetched after the vote, and still uses the old `total_score`.

This PR refresh the proposal's store, to get the new `total_score` after casting a vote, so any internal navigation after casting a vote use the updated proposal data.

This quick fix only resolve the issue with offchain spaces. We need a more complete solution to handle both offchain and onchain spaces, with onchain proposal refresh being triggered only after tx executed. Maybe an Event store

### How to test

1. Go to a proposal
2. Cast a vote
3. The RESULTS section in the sidebar should refresh and take the new vote into account
4. Go to the votes tab without refreshing the page
5. It should display your voting power percentage correctly

### CODE REVIEW

File: apps/ui/src/views/Proposal.vue [hunk 1]
```diff
@@ -83,6 +83,8 @@ async function handleVoteClick(choice: Choice) {
 
   try {
     await vote(proposal.value, choice);
+    // TODO: Quick fix only for offchain proposals, need a more complete solution for onchain proposals
+    proposalsStore.fetchProposal(spaceAddress.value!, id.value, networkId.value!);
```
Comment (Sekhmet) [inline apps/ui/src/views/Proposal.vue:87]: Can we guard it behind `offchainNetworks` check so we don't refetch SX spaces?

**Review by Sekhmet — APPROVED** [review]
tACK
